### ISSUE TITLE
SMA Plugin socket error

### ISSUE THREAD

**Issue by wil76** [smarthomeNG/smarthome#229]
I have restarted my tests with SMA Inverter monitoring under SmarthomeNG.
I get the following error running in debug mode:
2017-08-31 21:06:24 ERROR    __init__     sma          sma: establishing connection to inverter failed - module 'socket' has no attribute 'AF_BLUETOOTH' -- __init__.py:run:264
 
without debug no sma messages in the log

**Comment by psilo909** [comment]
for me this looks like missing bluetooth support in the operating system. did you install e.g. bluez?

**Comment by ohinckel** [comment]
This could be checked on plugin startup and when bluetooth is missing (e.g. checking if this constant exists) an error message should be logged.

**Comment by psilo909** [comment]
if someone wants to add this to the plugin feel free.. in my view this "thing" is still in beta or alpha. in my use cases i had to comment 3 lines of code in the  plugin to get it working. also sometimes i get crashes when starting up shng due to the plugin.. but looking at the big pile of code, currently i don't feel "enlightened" to maintain it..

**Comment by ohinckel** [comment]
Maybe @robert-budde can help here a little bit?

**Comment by robert-budde** [comment]
The plugin works absolutely stable in my environment - Beaglebone with my images and "normal" bluetooth module. The error mentioned above for sure comes from an unmet prerequisite. Debugging this plugin for every error somebody ever mentioned is not doable - every setup will differ slightly and above message can be regarded a "good" example: No platform, OS version or Bluetooth-hardware mentioned, in other more inverter centric cases even the inverter model is not mentioned. In the end, such a plugin can only mature by users willing to fix it based on their specific setup.

**Comment by psilo909** [comment]
@robert-budde what i am still unsure is why i had to comment lines 433-435 in my setting (there were discussions in the forum where i found out about that). now it is running fine, but before i always had the error message..

i also get sporadical errors by the plugin on the data retrieved from the inverter. it could be my "special" setting with a docker container on my synology nas and a bluetooth stick connected to it. the distance to the inverter is only 1 meter, so i don't think it is the signal. the errors also only show up sporadically when SmartHomeNG is starting up. once it is running the plugin is working..

**Comment by ohinckel** [comment]
> Debugging this plugin for every error somebody ever mentioned is not doable

Yes, right. But checking for a main requirement of the plugin - here Bluetooth - could be checked by the plugin. It's not a problem with a special environment or setup.

**Comment by psilo909** [comment]
@ohinckel in my view the message already provides enough information. if you use google, you should find out what the problem is. also the apt-get's are mentioned in the README.

**Comment by ohinckel** [comment]
Hey, it's OK to just close this issue. The internet provides a lot of information about how to fix it and of course the readme contains also instructions.

I just want to avoid such issues in the future. Users usually does not know what such an error means and it looks like a problem pr bug of the software.

Maybe I find some time to just add a check like this to the `__init__()` method:
```python
if (hasattr(socket, 'AF_BLUETOOTH')):
  raise Error("Python socket module does not support Bluetooth - see README.md how to install")
```

**Comment by psilo909** [comment]
@ohinckel adding more checks sure is ok.. 

but as written before: i think there are lots of other things preventing "normal" users from using the plugin. also have a look at the thread in the forum. 

it was developed to run in the environment of @robert-budde (where everything seems fine). but normally it shows up that this must not be true for other users having other inverter models. all i wanted to point out is, that there needs to be done more effort so that the plugin can be used "comfortable" also for new users and a broader bandwith of sma inverters.

i would be interested where all the information used in the plugin came from? e.g. parsing data retreived via bluetooth.

**Comment by ohinckel** [comment]
> all i wanted to point out is, that there needs to be done more effort so that the plugin can
> be used "comfortable" also for new users and a broader bandwith of sma inverters.

Yes, we can't check everything what could happen when the plugin is used. But Bluetooth support yes or no is really easy and a standard check. Does not depend on any hardware or protocol. Its in Python available or not.

For all the rest I would say "try googling or RTFM".

**Comment by psilo909** [comment]
@ohinckel agree.. perhaps i will work over my issues one day, but currently it is working most of the time and that's all what i need.. i have enough own plugins to care for.

**Comment by ohinckel** [comment]
For this I implemented a check as mentioned above. I think this is an easy check and only checks if the requirements are available. If not it hints the user to lookup the instructions in the README.md file.

**Comment by wil76** [comment]
but I followed the instructions in the README.
bluez is installed
and all checks documented in readme are working properly
but I still get this error

**Comment by psilo909** [comment]
@wil76 which platform are u using?

**Comment by wil76** [comment]
Linux on a Raspberry Pi 2
I'm using the image from "Onkel Andy":
https://sourceforge.net/p/smarthomeng-raspi-image/wiki/Home/

**Comment by wil76** [comment]
![image](https://user-images.githubusercontent.com/24221828/29994784-3bf6d24a-8fd8-11e7-9ab8-a888674263b5.png)

**Comment by psilo909** [comment]
i suppose the raspi2 has a bluetooth adapter connected via usb? how close is the inverter to the pi? can you connect from a PC using the SMA software?

**Comment by wil76** [comment]
it's working from my Windows PC via SUNNY EXPLORER 
but the connection is via a Repeater. 
obviously it's not a configuration problem.
thanks for you assistance; I will try further.

**Comment by ohinckel** [comment]
> but I still get this error

Which error? The Python error? If yes, you need to install the Python module with Bluetooth support. AFAIK, Python 3.3 supports this directly. Which Python version you're using currently?

Everything else seems to be a configuration issue and not related to SmartHomeNG and we should close this issue.

**Comment by psilo909** [comment]
does the pi also use the repeater? in the forum there were many comments on problems when using a repeater.

**Comment by wil76** [comment]
I'm aware of the repeater problem. 
but now with the new version of the plugin I would like to restart my testing and try to solve the Repeater problem.
I'm using the image from "Onkel Andy" it's based on Python 3.5.2 
and I still have the python problem: module 'socket' has no attribute 'AF_BLUETOOTH'

please close the issue; I will try to fix it myself

**Comment by ohinckel** [comment]
@onkelandy could you help here? Do you know why the Python version does not have the Bluetooth support?

**Comment by onkelandy** [comment]
As far as I remember the python version coming with the original Raspbian image was 3.4.
I've compiled 3.5.2 myself and obviously the bluetooth support isn't implemented automatically. There are three solutions to the problem ;)
a) Use Python 3.4 - you can either try to come up with virtualenv or just start smart home with python3.4 /usr/local/smarthome/bin/smarthome.py
b) Wait for the new image built on Raspbian Stretch including python 3.5.3 by default. Most likely bluetooth is available there. I'm doing final tests, the image might be released in a week I guess
c) @ohinckel I've read that socket using AF_BLUETOOTH is only available on Linux. As there is a patch out there that makes SmarthomeNG run on Mac OS X it might be a good idea to rely on modules that are also supported by other OS?

**Comment by ohinckel** [comment]
> it might be a good idea to rely on modules that are also supported by other OS?

Which modules do you mean? AFAIK, the plugin is using a specific interface (`socket` module). Do these other modules share same interface? And can they be used by the plugin?

**Comment by onkelandy** [comment]
I guess socket is not the issue, but the bluetooth part of it. I've read several times something like this:
https://stackoverflow.com/questions/36178389/python-socket-bluetooth

So maybe pybluez would be a more universal approach.. But as I don't use the plugin or bluetooth with python I can't verify.

@wil76 with the newest 2.0 image everything should be fine using python 3.5.3

**Comment by ohinckel** [comment]
I guess we can close this now, right?

**Comment by wil76** [comment]
Yes, please close.

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Dezember 2017 21:06
An: smarthomeNG/smarthome <smarthome@noreply.github.com>
Cc: wil76 <wheynen@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [smarthomeNG/smarthome] SMA Plugin socket error (#229)

 

I guess we can close this now, right?
